/**
 * NEURO·FAST SOVEREIGN — INDUSTRIAL SKU CATALOG
 * High-fidelity inventory mesh for strategic node population.
 */

export const INITIAL_INVENTORY_MESH = [
  { name: "Organic Milk 1L", category: "Fresh", costPrice: 45, sellingPrice: 65, reorderPoint: 10, sku: "SKU-MILK-01", currentStock: 25 },
  { name: "Whole Wheat Bread", category: "Fresh", costPrice: 30, sellingPrice: 50, reorderPoint: 15, sku: "SKU-BREAD-01", currentStock: 30 },
  { name: "Farm Fresh Eggs (12)", category: "Fresh", costPrice: 60, sellingPrice: 90, reorderPoint: 8, sku: "SKU-EGGS-01", currentStock: 20 },
  { name: "Salted Butter 200g", category: "Fresh", costPrice: 80, sellingPrice: 110, reorderPoint: 5, sku: "SKU-BUTTER-01", currentStock: 15 },
  { name: "Greek Yogurt 500g", category: "Fresh", costPrice: 70, sellingPrice: 120, reorderPoint: 6, sku: "SKU-YOGURT-01", currentStock: 18 },
  { name: "Mineral Water 1L", category: "Beverages", costPrice: 10, sellingPrice: 20, reorderPoint: 50, sku: "SKU-WATER-01", currentStock: 100 },
  { name: "Cola 500ml", category: "Beverages", costPrice: 25, sellingPrice: 40, reorderPoint: 24, sku: "SKU-COLA-01", currentStock: 48 },
  { name: "Orange Juice 1L", category: "Beverages", costPrice: 80, sellingPrice: 130, reorderPoint: 12, sku: "SKU-JUICE-01", currentStock: 24 },
  { name: "Potato Chips 150g", category: "Snacks", costPrice: 20, sellingPrice: 45, reorderPoint: 30, sku: "SKU-CHIPS-01", currentStock: 60 },
  { name: "Chocolate Chip Cookies", category: "Snacks", costPrice: 40, sellingPrice: 75, reorderPoint: 20, sku: "SKU-COOKIES-01", currentStock: 40 },
  { name: "Dark Chocolate 100g", category: "Snacks", costPrice: 90, sellingPrice: 180, reorderPoint: 10, sku: "SKU-CHOC-01", currentStock: 25 },
  { name: "Basmati Rice 5kg", category: "Pantry", costPrice: 400, sellingPrice: 650, reorderPoint: 5, sku: "SKU-RICE-01", currentStock: 10 },
  { name: "Pasta Penne 500g", category: "Pantry", costPrice: 50, sellingPrice: 95, reorderPoint: 15, sku: "SKU-PASTA-01", currentStock: 30 },
  { name: "Red Lentils 1kg", category: "Pantry", costPrice: 80, sellingPrice: 130, reorderPoint: 10, sku: "SKU-LENTIL-01", currentStock: 25 },
  { name: "Sunflower Oil 1L", category: "Pantry", costPrice: 120, sellingPrice: 185, reorderPoint: 12, sku: "SKU-OIL-01", currentStock: 20 },
  { name: "All Purpose Flour 2kg", category: "Pantry", costPrice: 60, sellingPrice: 110, reorderPoint: 8, sku: "SKU-FLOUR-01", currentStock: 15 },
  { name: "Refined Sugar 1kg", category: "Pantry", costPrice: 40, sellingPrice: 60, reorderPoint: 20, sku: "SKU-SUGAR-01", currentStock: 40 },
  { name: "Sea Salt 1kg", category: "Pantry", costPrice: 15, sellingPrice: 30, reorderPoint: 10, sku: "SKU-SALT-01", currentStock: 50 },
  { name: "Instant Coffee 100g", category: "Pantry", costPrice: 150, sellingPrice: 280, reorderPoint: 10, sku: "SKU-COFFEE-01", currentStock: 12 },
  { name: "Green Tea (25 Bags)", category: "Pantry", costPrice: 100, sellingPrice: 190, reorderPoint: 15, sku: "SKU-TEA-01", currentStock: 20 },
  { name: "Shampoo 400ml", category: "Personal Care", costPrice: 180, sellingPrice: 320, reorderPoint: 5, sku: "SKU-SHAMPOO-01", currentStock: 10 },
  { name: "Bath Soap 125g", category: "Personal Care", costPrice: 25, sellingPrice: 45, reorderPoint: 20, sku: "SKU-SOAP-01", currentStock: 50 },
  { name: "Toothpaste 150g", category: "Personal Care", costPrice: 60, sellingPrice: 95, reorderPoint: 12, sku: "SKU-PASTE-01", currentStock: 30 },
  { name: "Hand Wash Refill 750ml", category: "Personal Care", costPrice: 90, sellingPrice: 160, reorderPoint: 10, sku: "SKU-HANDWASH-01", currentStock: 15 },
  { name: "Face Wash 100ml", category: "Personal Care", costPrice: 110, sellingPrice: 210, reorderPoint: 8, sku: "SKU-FACEWASH-01", currentStock: 12 },
  { name: "Laundry Detergent 1kg", category: "Home Care", costPrice: 140, sellingPrice: 240, reorderPoint: 10, sku: "SKU-DETERGENT-01", currentStock: 20 },
  { name: "Dishwash Liquid 500ml", category: "Home Care", costPrice: 70, sellingPrice: 120, reorderPoint: 15, sku: "SKU-DISHWASH-01", currentStock: 25 },
  { name: "Glass Cleaner 500ml", category: "Home Care", costPrice: 65, sellingPrice: 105, reorderPoint: 5, sku: "SKU-GLASS-01", currentStock: 10 },
  { name: "Floor Cleaner 1L", category: "Home Care", costPrice: 110, sellingPrice: 190, reorderPoint: 8, sku: "SKU-FLOOR-01", currentStock: 15 },
  { name: "Toilet Cleaner 750ml", category: "Home Care", costPrice: 85, sellingPrice: 145, reorderPoint: 10, sku: "SKU-TOILET-01", currentStock: 12 },
  { name: "Apples (1kg)", category: "Fresh", costPrice: 120, sellingPrice: 180, reorderPoint: 15, sku: "SKU-APPLE-01", currentStock: 20 },
  { name: "Bananas (6 pcs)", category: "Fresh", costPrice: 30, sellingPrice: 50, reorderPoint: 20, sku: "SKU-BANANA-01", currentStock: 25 },
  { name: "Tomatoes (1kg)", category: "Fresh", costPrice: 25, sellingPrice: 45, reorderPoint: 30, sku: "SKU-TOMATO-01", currentStock: 40 },
  { name: "Onions (1kg)", category: "Fresh", costPrice: 35, sellingPrice: 60, reorderPoint: 40, sku: "SKU-ONION-01", currentStock: 50 },
  { name: "Potatoes (1kg)", category: "Fresh", costPrice: 20, sellingPrice: 40, reorderPoint: 50, sku: "SKU-POTATO-01", currentStock: 60 },
  { name: "Chicken Breast 500g", category: "Fresh", costPrice: 180, sellingPrice: 260, reorderPoint: 5, sku: "SKU-CHICKEN-01", currentStock: 8 },
  { name: "Frozen Peas 500g", category: "Frozen", costPrice: 60, sellingPrice: 110, reorderPoint: 10, sku: "SKU-PEAS-01", currentStock: 20 },
  { name: "Ice Cream 500ml", category: "Frozen", costPrice: 120, sellingPrice: 220, reorderPoint: 8, sku: "SKU-ICECREAM-01", currentStock: 15 },
  { name: "Frozen Pizza", category: "Frozen", costPrice: 150, sellingPrice: 290, reorderPoint: 6, sku: "SKU-PIZZA-01", currentStock: 10 },
  { name: "Instant Noodles (4pk)", category: "Snacks", costPrice: 40, sellingPrice: 75, reorderPoint: 25, sku: "SKU-NOODLES-01", currentStock: 50 },
  { name: "Mayonnaise 250g", category: "Pantry", costPrice: 70, sellingPrice: 125, reorderPoint: 10, sku: "SKU-MAYO-01", currentStock: 15 },
  { name: "Ketchup 500g", category: "Pantry", costPrice: 85, sellingPrice: 140, reorderPoint: 12, sku: "SKU-KETCHUP-01", currentStock: 20 },
  { name: "Honey 250g", category: "Pantry", costPrice: 130, sellingPrice: 240, reorderPoint: 5, sku: "SKU-HONEY-01", currentStock: 10 },
  { name: "Peanut Butter 340g", category: "Pantry", costPrice: 160, sellingPrice: 290, reorderPoint: 5, sku: "SKU-PB-01", currentStock: 12 },
  { name: "Oats 1kg", category: "Pantry", costPrice: 140, sellingPrice: 230, reorderPoint: 8, sku: "SKU-OATS-01", currentStock: 15 },
  { name: "Corn Flakes 500g", category: "Pantry", costPrice: 110, sellingPrice: 195, reorderPoint: 10, sku: "SKU-CORNFLAKES-01", currentStock: 18 },
  { name: "Napkins (50 pcs)", category: "Home Care", costPrice: 40, sellingPrice: 85, reorderPoint: 20, sku: "SKU-NAPKIN-01", currentStock: 40 },
  { name: "Aluminum Foil", category: "Home Care", costPrice: 90, sellingPrice: 160, reorderPoint: 5, sku: "SKU-FOIL-01", currentStock: 10 },
  { name: "AA Batteries (4pk)", category: "Electronics", costPrice: 120, sellingPrice: 220, reorderPoint: 10, sku: "SKU-BATTERY-01", currentStock: 25 },
  { name: "Garbage Bags (15)", category: "Home Care", costPrice: 50, sellingPrice: 110, reorderPoint: 15, sku: "SKU-GARBAGE-01", currentStock: 30 },
  { name: "Kitchen Sponge (3pk)", category: "Home Care", costPrice: 35, sellingPrice: 75, reorderPoint: 12, sku: "SKU-SPONGE-01", currentStock: 20 },
  { name: "Spaghetti 500g", category: "Pantry", costPrice: 55, sellingPrice: 100, reorderPoint: 15, sku: "SKU-SPAGHETTI-01", currentStock: 25 },
  { name: "Tomato Sauce 400g", category: "Pantry", costPrice: 45, sellingPrice: 80, reorderPoint: 15, sku: "SKU-TOMATOSAUCE-01", currentStock: 20 },
  { name: "Black Pepper 50g", category: "Pantry", costPrice: 60, sellingPrice: 120, reorderPoint: 5, sku: "SKU-PEPPER-01", currentStock: 15 },
  { name: "Turmeric Powder 100g", category: "Pantry", costPrice: 30, sellingPrice: 60, reorderPoint: 10, sku: "SKU-TURMERIC-01", currentStock: 20 }
];
