export const SKUS = [
  {
    id: 'SKU-001',
    name: 'Artisan Whole Wheat Bread',
    category: 'Bakery',
    currentStock: 12,
    predictedDemand4Hours: 18,
    salesVelocity24Hours: 45,
    supplierLeadTimeDays: 1,
    minimumOrderQuantity: 20,
    unitPrice: 3.5,
    supplierName: 'Sunrise Bakeries',
    status: 'low',
  },
  {
    id: 'SKU-002',
    name: 'Organic Full Cream Milk (1L)',
    category: 'Dairy',
    currentStock: 8,
    predictedDemand4Hours: 15,
    salesVelocity24Hours: 68,
    supplierLeadTimeDays: 1,
    minimumOrderQuantity: 24,
    unitPrice: 2.1,
    supplierName: 'Green Pastures Dairy',
    status: 'critical',
  },
  {
    id: 'SKU-003',
    name: 'Fresh Hass Avocado (2-pack)',
    category: 'Produce',
    currentStock: 34,
    predictedDemand4Hours: 12,
    salesVelocity24Hours: 28,
    supplierLeadTimeDays: 2,
    minimumOrderQuantity: 10,
    unitPrice: 4.8,
    supplierName: 'Valley Fresh Produce',
    status: 'healthy',
  },
  {
    id: 'SKU-004',
    name: 'Bottled Spring Water (500ml)',
    category: 'Beverages',
    currentStock: 156,
    predictedDemand4Hours: 40,
    salesVelocity24Hours: 210,
    supplierLeadTimeDays: 3,
    minimumOrderQuantity: 100,
    unitPrice: 0.85,
    supplierName: 'Clear Springs Co',
    status: 'healthy',
  },
  {
    id: 'SKU-005',
    name: 'Instant Coffee Blend (200g)',
    category: 'Pantry',
    currentStock: 5,
    predictedDemand4Hours: 7,
    salesVelocity24Hours: 12,
    supplierLeadTimeDays: 5,
    minimumOrderQuantity: 12,
    unitPrice: 7.5,
    supplierName: 'Global Bean Imports',
    status: 'critical',
  },
];

export const SALES_TRENDS = [
  { time: '08:00', sales: 12 },
  { time: '09:00', sales: 18 },
  { time: '10:00', sales: 25 },
  { time: '11:00', sales: 30 },
  { time: '12:00', sales: 42 },
  { time: '13:00', sales: 38 },
  { time: '14:00', sales: 31 },
  { time: '15:00', sales: 27 },
];

export const RECENT_SALES = [
  { timestamp: new Date(Date.now() - 3600000).toISOString(), quantity: 2 },
  { timestamp: new Date(Date.now() - 7200000).toISOString(), quantity: 5 },
  { timestamp: new Date(Date.now() - 10800000).toISOString(), quantity: 3 },
  { timestamp: new Date(Date.now() - 14400000).toISOString(), quantity: 1 },
];